CREATE TABLE thesis.procedure (
	procedure_id SERIAL,
	name_est VARCHAR(256) NOT NULL,
	name_eng VARCHAR(256) NOT NULL,
	archived BOOLEAN NOT NULL DEFAULT FALSE,
	PRIMARY KEY (procedure_id)
);

INSERT INTO thesis.procedure (name_est, name_eng)
VALUES
	('Gaasi koostis', 'Composition of gases'),
	('Süsivesinikute koostise määramine', 'Hydrocarbons content'),
	('Väävliühendite määramine', 'Sulfur compounds content'),
	('Plii sisaldus', 'Content of lead'),
	('Komponeendiline koostis', 'Component composition'),
	('Benseen', 'Benzene'),
	('Naatriumi ja kaaliumi sisaldus', 'Sodium and potassium contents'),
	('Rasvhappe metüülestrid (FAME)', 'Fatty acid methyl esters (FAME)'),
	('Infrapunaspektroskoopia*', 'Infrared spectroscopy*'),
	('Al, Ca, Fe, Mg, K, Si, Na, Ti sisaldus', 'Al, Ca, Fe, Mg, K, Si, Na, Ti contents'),
	('Al, Ca, Fe, Si, Na, V, Zn sisaldus', 'Al, Ca, Fe, Si, Na, V, Zn contents'),
	('Põhielementide (Al, Ca, Fe, Mg, K, Si, Na, Ti) sisaldus MP-AES meetodiga', 'Major elements (Al, Ca, Fe, Mg, K, Si, Na, Ti) content by MP-AES method'),
	('Naatriumi ja kaalium', 'Sodium and potassium'),
	('Elementide (Ca, Fe, K, Na, Ni, Si, Zn, Al, Mg, Mn, Cd, B, Ti, Ba, Co, Sr, Cu, Cr, V, Pb ja As) sisaldus', 'Elements (Ca, Fe, K, Na, Ni, Si, Zn, Al, Mg, Mn, Cd, B, Ti, Ba, Co, Sr, Cu, Cr, V, Pb and As) content'),
	('Kaadmiumi, vase, nikli, plii, koobalti, tsingi sisaldus', 'Cadmium, copper, nickel, lead, cobalt, zinc content '),
	('Kaltsiumi (Ca) ja magneesiumi (Mg) sisaldus', 'Calcium (Ca) and Magnesium (Mg) content '),
	('Summaarsete fenoolid', 'Total phenols'),
	('Fenooliindeks', 'Phenol index '),
	('Naftaproduktid', 'Petroleum products '),
	('Tolueen', 'Toluene'),
	('Benzoflex® sisalduse määramine naftasaaduste foonil', 'Determination of Benzoflex® content in presence of petroleum products'),
	('Mangaani ja naatriumi sisaldus', 'Content of manganese and sodium'),
	('Üldsüsinik (TC)', 'Total carbon (TC)'),
	('Üldanorgaaniline süsinik (TIC)', 'Total inorganic carbon (TIC)'),
	('Üldorgaanilise süsinik (TOC)', 'Total organic carbon (TOC)'),
	('Üldsüsinik, vesinik, lämmastik määramine instrumentaalsel meetodil', 'Total Carbon, Hydrogen, Nitrogen determination by instrumental method'),
	('Süsinik, vesinik ja lämmastik, instrumentaalne määramine', 'Carbon, Hydrogen, Nitrogen instrumental determination'),
	('Üldväävel', 'Total sulphur'),
	('Üldväävel', 'Total sulphur'),
	('Väävel, määramine ultraviolett fluorestsents meetodil', 'Sulfur, determination by ultraviolet fluorescence method'),
	('Väävlisisaldus', 'Sulphur content'),
	('Fluoori sisaldus', 'Content of fluorine'),
	('Fluor', 'Fluor'),
	('Fluor', 'Fluor'),
	('Hapniku sisaldus', 'Content of oxygen'),
	('Hapniku sisaldus', 'Content of oxygen'),
	('Kloori sisaldus (elementanalüsaator)', 'Content of chlorine by elemental analyser'),
	('Kloor, määramine Eschka meetodil', 'Chlorine determination by Eschka method'),
	('Proovi ettevalmistus', 'Preparation of samples'),
	('Proovi jagamine samaväärsteks osadeks proovijaoti abil', 'Sample dividing into equal portions using sample splitter'),
	('Granulomeetriline koostis', 'Granulometric distribution'),
	('Üldniiskus', 'Total moisture'),
	('Analüütiline niiskus', 'Moisture, in general analysis sample'),
	('Tuhasus', 'Ash'),
	('Lenduvained', 'Volatile matter'),
	('Väävli sidevormid', 'Content of bonding forms of sulfur'),
	('Utmise produktide saagis', 'Semi-coking products yields'),
	('Sulfaattuha määramine', 'Determination of sulfated ash'),
	('Tuhasus', 'Ash'),
	('Tahkete lisandite sisaldus ja tuhasus', 'Sediment content and ash'),
	('Lahustumatute lisandite sisaldus', 'Content of insoluble impurities'),
	('Termogravimeetriline analüüs (TGA)', 'Thermogravimetric analysis (TGA)'),
	('Happearv, määramine värvusindikaatori tiitrimise meetodil', 'Acid number, determination by colour-indicator titration method'),
	('Veesisaldus Karl Fischeri meetodil', 'Water content by Karl Fischer Mehod'),
	('Joodiarv', 'Iodine value'),
	('Karbonaatne süsinik (CO2)', 'Carbon dioxide'),
	('Keemiline hapnikutarve (KHT)', 'Chemical oxygen demand (COD)'),
	('Osakeste suuruse jaotuse määramine (0,01-3500 µm)', 'Detrmination of particle size distribution (0,01-3500 µm)'),
	('Fraktsioonkoostis normaalrõhul, määramine käsitsi meetodil', 'Distillation characteristics at atmospheric pressure, determination by manual method'),
	('Leekpunkt, määramine Pensky-Martensi suletud tiiglis', 'Flash point, determination in Pensky-Martens closed cup'),
	('Leekpunkt lahtises tiiglis', 'Flash point in open cup'),
	('Kinemaatiline viskoossus, määramine; dünaamiline viskoossus, arvutamine', 'Kinematic viscosity, determination; dynamic viscosity, the calculation'),
	('Tihedus areomeetrilisel meetodil', 'Density by areometrical method'),
	('Tihedus, määramine ostsilleeruva U-toru meetodil', 'Density, determination by U-oscillating tube method'),
	('Veesisaldus, määramine destillatsioonimeetodil', 'Water content, determination by distillation method'),
	('Määrimisomadused HFRR seadmega', 'Lubricity by the high-frequency reciprocating (HFRR device)'),
	('Korrosiivsus vaskplaadikatsel', 'Corrosiveness to Copper by Copper strip test'),
	('Hangumispunkt', 'Pour point'),
	('Külmfiltri ummistuspunkt (CFPP)', 'Cold filter plugging point (CFPP)'),
	('Hägustumispunkt', 'Cloud point'),
	('Küllastunud aururõhk', 'Air saturated vapour pressure'),
	('Vaigusisaldus (pihustusaurutusmeetod)', 'Gum content (by jet evaporation method)'),
	('10% destillatsioonijäägi koksiarv', 'Carbon residue (on 10% distillation residue)'),
	('Põlemissoojus, määramine kalorimeetrilise pommi meetodil', 'Head of combustion, determination by bomb calorimeter'),
	('Ülemine kütteväärtus, määramine kalorimeetrilise pommi meetodil', 'Gross calorific value, determination by calorimeter bomb method'),
	('Üldlämmastiku (Nüld) määramine. Modifitseeritud Kjeldahl', 'Determination of total nitrogen (Ntot). Modified Kjeldahl method'),
	('pH määramine', 'Determination of pH'),
	('Alumine ja ülemine põlemissoojus', 'Net and Gross Heat of Combustion'),
	('Tsetaaniindeks', 'Cetane index'),
	('Tahkete kütuste töötlemine (suur retort)', 'Processing of solid fuels (big retort)'),
	('Tahkete kütuste töötlemine (retort tahke soojuskandjaga)', 'Processing of solid fuels (by solid heat carrier)'),
	('Materjalide töötlemine kõrgsurvereaktoris', 'Processing of materials in high-pressure autoclave'),
	('Hüdrogeenimine läbivoolu torureaktoris', 'Hydrogenation in tubular flow-reactor'),
	('Rektifikatsioon', 'Rectification'),
	('Heitgaaside uuringud erinevate kütustega töötamisel (CO, CO2, NO2, NO, NOx, SO2, HC)', 'Reasearches of exhaust gases by testing with different fuels (CO, CO2, NO, NOx, SO2, O2)'),
	('Mootori töönäitajate uuringud erinevate kütustega töötamisel', 'Reasearches of motor performance parameters by testing with different fuels')
;