CREATE TABLE thesis.sample (
	sample_id SERIAL,
	name_est VARCHAR(256) NOT NULL,
	name_eng VARCHAR(256) NOT NULL,
	archived BOOLEAN NOT NULL DEFAULT FALSE,
	PRIMARY KEY (sample_id)
);

INSERT INTO thesis.sample (name_est, name_eng)
VALUES
	('antratsiit', 'anthracite'),
	('bensiin', 'petrol'),
	('biodiislikütus', 'biodiesel fuel'),
	('biogaas', 'biogas'),
	('biokütused', 'biofuels'),
	('diislikütus', 'diesel'),
	('ehitusmaterjalid', 'building materials'),
	('granuleeritud materjalid', 'granular materials'),
	('heitgaas', 'exhaust gas'),
	('heitvesi', 'waste water'),
	('jäätmed', 'waste'),
	('kaaliumbensoaat', 'potassium benzoate'),
	('kerge kütteõli', 'light fuel oil'),
	('kivisüsi', 'coal'),
	('koks', 'coke'),
	('kütteõli', 'domestic heating fuel'),
	('kütuste töötlemise saadused', 'fuel processing products'),
	('laevakütused', 'marine fuels'),
	('lenduvad naftasaadused', 'volatile petroleum products'),
	('lennukikütus', 'aviation fuel'),
	('ligniit', 'lignite'),
	('maagaas', 'natural gas'),
	('muud süsivesinikud', 'other hydrocarbons'),
	('määrdeained', 'lubricants'),
	('määrdeõlid', 'lubricant oils'),
	('naftasaadused', 'petroleum products'),
	('naftasaadused (destilleerub < 390°C)', 'petroleum products (distilled <390 ° C)'),
	('naftasaaduste lisandid', 'additives of petroleum products'),
	('pinnas', 'soil'),
	('plastikud', 'plastics'),
	('plastjäätmed', 'plastic wastes'),
	('polümeerid', 'polymer'),
	('poolkoks', 'semi-coke'),
	('pruunsüsi', 'brown coal'),
	('puit', 'wood chips'),
	('pulbrilised materjalid', 'powdered materials'),
	('põlevkivi', 'oil shale'),
	('põlevkiviõli', 'shale oil'),
	('põlevkiviõli fraktsioonid', 'shale oil fractions'),
	('raske kütteõli', 'heavy fuel oil'),
	('rasv', 'fat'),
	('rasvhappe metüülestrid (FAME)', 'Fatty Acid Methyl Esters (FAME)'),
	('rehvihakke', 'tire chips'),
	('reoveesetted', 'sewage sludge'),
	('setted', 'sediments'),
	('Stoddard lahustid', 'Stoddard solvents'),
	('süsi', 'coal'),
	('süsivesinike diislikütus', 'hydrocarbon diesel fuel'),
	('süsivesinike kütteõli (tihedusega 750...1000 kg/m3)', 'hydrocarbons fuel oil (density range 750...1000 kg/m3)'),
	('šlakid', 'sludge'),
	('tahked biokütused', 'solid recovered fuels (SRF)'),
	('tahked jäätmed', 'solid waste'),
	('tahked jäätmekütused', 'refuse derived fuels (RDF)'),
	('tahked mineraalkütused', 'solid mineral fuels'),
	('tahked produktid', 'solid products'),
	('tahked proovid', 'solid samples'),
	('taimne materjal', 'plant material'),
	('toornafta', 'crude oil'),
	('tuhk', 'ash'),
	('turvas', 'peat'),
	('vedelad kütused keemistemperatuuriga kuni 320 °C', 'liquid fuels with boiling point up to 320 °C'),
	('vedelad kütused keemistemperatuuriga kuni 340 °C', 'liquid fuels with boiling point up to 340 °C'),
	('vedelad naftasaadused', 'liquid petroleum products'),
	('vedelad produktid', 'liquid products'),
	('vedelad proovid', 'liquid samples'),
	('vedelad põlevkivitooted', 'liquid oil shale products'),
	('vedelad süsivesinikkütused', 'liquid hydrocarbon fuels'),
	('veeproovid', 'water samples'),
	('muu', 'other')
;